# Generated by Django 5.1.4 on 2024-12-28 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftidea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occasion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftidea',
            name='occasions',
            field=models.ManyToManyField(blank=True, related_name='gift_ideas', to='core.occasion'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftidea',
            name='recipients',
            field=models.ManyToManyField(related_name='gift_ideas', to='core.recipient'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='interests',
            field=models.ManyToManyField(related_name='interested_recipients', to='core.tag'),
        ),
        migrations.AddField(
            model_name='giftidea',
            name='tags',
            field=models.ManyToManyField(related_name='gift_ideas', to='core.tag'),
        ),
    ]
