# Generated by Django 5.1.4 on 2024-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftidea',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('gifted', 'Gifted')], default='idea', max_length=20),
        ),
    ]
