# Generated by Django 5.1.4 on 2025-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_giftidea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftidea',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
