# Generated by Django 5.1.4 on 2025-01-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='encrypted_openai_key',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='openai_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
