# Generated by Django 5.1.4 on 2025-01-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_userpreferences_encrypted_openai_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='current_ai_model',
            field=models.CharField(choices=[('none', 'No model'), ('openai', 'OpenAI'), ('deepseek', 'Deepseek')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='deepseek_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
