# Generated by Django 5.1.4 on 2025-01-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpreferences_current_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='deepseek_model',
            field=models.CharField(blank=True, default='deepseek-chat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-3.5-turbo', max_length=50, null=True),
        ),
    ]
