# Generated by Django 5.1.4 on 2025-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_purchaserecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftidea',
            name='notes',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
